### ISSUE TITLE
Docker without MongoDB replica

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Embedded.arm64#6]
What is the MongoDB replica need for? Is it absolutely required? As far as I know, the normal Rocket Chat image doesn't need both a main and a replica container running at the same time.

**Comment by Sing-Li** [comment]
Can you explain what MongoDB replica are you referring to @UnleavenedEagle ?   And which "normal Rocket.Chat image" are you referring to 🤔

**Comment by ghost** [comment]
Replica = mongo-init-replica in [docker-compose.yml](https://github.com/RocketChat/Rocket.Chat.Embedded.arm64/blob/develop/docker/compose/docker-compose.yml)
Normal image = [rocket.chat](https://hub.docker.com/_/rocket-chat) in Docker Registry

**Comment by Sing-Li** [comment]
This is the official image repository ...  docker-compose.yml is totally independent of the image; BUT even in our  "official image repository" you will see this:

https://github.com/RocketChat/Docker.Official.Image/blob/master/docker-compose.yml

It is a ONE TIME operation that must be performed the first time Rocket.Chat starts.
